export const seedExpenses = [
  // Japón — reconstruye el mock de Figma (Hoy $575.000, Ayer $1.300.000) más días previos
  // hasta sumar el total de 5.750.000 que ya tenía el viaje semilla.
  {
    id: 'japon-1',
    tripId: 'japon',
    description: 'Vuelo a Japón',
    categoryId: 'transport',
    paymentMethodId: 'card',
    amount: 1_200_000,
    currency: 'COP',
    date: '2026-08-12',
  },
  {
    id: 'japon-2',
    tripId: 'japon',
    description: 'Hotel Shibuya (primeras noches)',
    categoryId: 'lodging',
    paymentMethodId: 'card',
    amount: 1_500_000,
    currency: 'COP',
    date: '2026-08-13',
  },
  {
    id: 'japon-3',
    tripId: 'japon',
    description: 'Compras en Akihabara',
    categoryId: 'general',
    paymentMethodId: 'card',
    amount: 675_000,
    currency: 'COP',
    date: '2026-08-14',
  },
  {
    id: 'japon-4',
    tripId: 'japon',
    description: 'Cena ramen y entradas al templo',
    categoryId: 'food',
    paymentMethodId: 'cash',
    amount: 500_000,
    currency: 'COP',
    date: '2026-08-15',
  },
  {
    id: 'japon-5',
    tripId: 'japon',
    description: 'Hospedaje Shibuya',
    categoryId: 'lodging',
    paymentMethodId: 'card',
    amount: 500_000,
    currency: 'COP',
    originalAmount: 25_430,
    originalCurrency: 'JPY',
    date: '2026-08-16',
  },
  {
    id: 'japon-6',
    tripId: 'japon',
    description: 'Almuerzo',
    categoryId: 'food',
    paymentMethodId: 'card',
    amount: 250_000,
    currency: 'COP',
    originalAmount: 12_715,
    originalCurrency: 'JPY',
    date: '2026-08-16',
  },
  {
    id: 'japon-7',
    tripId: 'japon',
    description: 'Taxi',
    categoryId: 'entertainment',
    paymentMethodId: 'card',
    amount: 350_000,
    currency: 'COP',
    originalAmount: 17_801,
    originalCurrency: 'JPY',
    date: '2026-08-16',
  },
  {
    id: 'japon-8',
    tripId: 'japon',
    description: 'Pelea sumos',
    categoryId: 'entertainment',
    paymentMethodId: 'card',
    amount: 200_000,
    currency: 'COP',
    originalAmount: 10_172,
    originalCurrency: 'JPY',
    date: '2026-08-16',
  },
  {
    id: 'japon-9',
    tripId: 'japon',
    description: 'Cena en restaurante',
    categoryId: 'food',
    paymentMethodId: 'cash',
    amount: 145_000,
    currency: 'COP',
    originalAmount: 7_375,
    originalCurrency: 'JPY',
    date: '2026-08-17',
  },
  {
    id: 'japon-10',
    tripId: 'japon',
    description: 'Taxi',
    categoryId: 'transport',
    paymentMethodId: 'cash',
    amount: 80_000,
    currency: 'COP',
    originalAmount: 65_000,
    originalCurrency: 'JPY',
    date: '2026-08-17',
  },
  {
    id: 'japon-11',
    tripId: 'japon',
    description: 'Karaoke',
    categoryId: 'entertainment',
    paymentMethodId: 'card',
    amount: 200_000,
    currency: 'COP',
    originalAmount: 10_172,
    originalCurrency: 'JPY',
    date: '2026-08-17',
  },
  {
    id: 'japon-12',
    tripId: 'japon',
    description: 'Mangas',
    categoryId: 'general',
    paymentMethodId: 'card',
    amount: 150_000,
    currency: 'COP',
    originalAmount: 7_629,
    originalCurrency: 'JPY',
    date: '2026-08-17',
  },

  // Resto de viajes semilla: un gasto único que conserva el total que ya mostraba el hub.
  {
    id: 'cartagena-1',
    tripId: 'cartagena',
    description: 'Gastos del viaje',
    categoryId: 'general',
    paymentMethodId: 'cash',
    amount: 450_000,
    currency: 'COP',
    date: '2026-09-05',
  },
  {
    id: 'lisboa-1',
    tripId: 'lisboa',
    description: 'Gastos del viaje',
    categoryId: 'general',
    paymentMethodId: 'cash',
    amount: 1_200_000,
    currency: 'COP',
    date: '2026-10-02',
  },
  {
    id: 'medellin-1',
    tripId: 'medellin',
    description: 'Gastos del viaje',
    categoryId: 'general',
    paymentMethodId: 'cash',
    amount: 1_150_000,
    currency: 'COP',
    date: '2026-06-01',
  },
  {
    id: 'rio-1',
    tripId: 'rio',
    description: 'Gastos del viaje',
    categoryId: 'general',
    paymentMethodId: 'cash',
    amount: 5_980_000,
    currency: 'COP',
    date: '2026-04-10',
  },
];
